// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuNiPBatirU67igRhNxT65y-wwkuE9d38',
    appId: '1:1058809554389:web:45fc693c4d3439b2fbc95c',
    messagingSenderId: '1058809554389',
    projectId: 'shareabite-b9864',
    authDomain: 'shareabite-b9864.firebaseapp.com',
    storageBucket: 'shareabite-b9864.appspot.com',
    measurementId: 'G-BHFQBT8Z9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFg2RaWMl4xs2RxWvzw4Yy9yTlRf_bcA',
    appId: '1:1058809554389:android:2d8fe76fb8dee30dfbc95c',
    messagingSenderId: '1058809554389',
    projectId: 'shareabite-b9864',
    storageBucket: 'shareabite-b9864.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG1eIevwIceEheOn5RxDh2Rd1jFyCaS_A',
    appId: '1:1058809554389:ios:b2dcf62a8b8a7afdfbc95c',
    messagingSenderId: '1058809554389',
    projectId: 'shareabite-b9864',
    storageBucket: 'shareabite-b9864.appspot.com',
    iosClientId: '1058809554389-q7jkprd7k2pfgt87er13e7nc54k0lvf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareabite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG1eIevwIceEheOn5RxDh2Rd1jFyCaS_A',
    appId: '1:1058809554389:ios:b2dcf62a8b8a7afdfbc95c',
    messagingSenderId: '1058809554389',
    projectId: 'shareabite-b9864',
    storageBucket: 'shareabite-b9864.appspot.com',
    iosClientId: '1058809554389-q7jkprd7k2pfgt87er13e7nc54k0lvf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareabite',
  );
}
